<?php

return [
    'brand' => [
        'site_name' => 'Our Care Pty Ltd',
        'tagline' => 'Your Care, Your Wellness',
        'logo' => 'logo3.png',
        'phone' => '0425 795 830',
        'email' => 'admin@ourcarepty.com',
        'sign_in_label' => 'Sign in',
        'create_account_label' => 'Create account',
        'updates_label' => 'NDIS Updates',
        'updates_url' => '/services-v2#ndis',
        'footer_services_label' => 'Services',
        'footer_quick_links_label' => 'Quick Links',
        'footer_contact_label' => 'Contact',
    ],

    'palette' => [
        'primary' => '#2d124b',
        'secondary' => '#e6badf',
        'accent' => '#ff7044',
        'background' => '#fffaf7',
        'surface' => '#fff8f2',
        'text' => '#2c1746',
    ],

    'pages' => [
        'home-v2' => [
            'label' => 'Home',
            'title' => 'Our Care Pty Ltd',
            'hero_title' => 'The caring choice for NDIS support in Australia',
            'hero_subtitle' => 'Plan your support, connect with trusted workers, and build routines that protect dignity, independence, and everyday wellbeing.',
            'hero_image' => 'hero.jpg',
            'intro_title' => 'NDIS and community support services in Australia',
            'intro_text' => "Our Care helps people find reliable support for daily living, personal care, community participation, transport, counselling, respite, and capacity building.\n\nWe keep the process clear from first enquiry through intake, worker matching, onboarding, and ongoing service coordination.",
            'sections' => [
                ['title' => 'Daily Support', 'text' => 'Personal care, domestic assistance, routines, and everyday support delivered with respect.'],
                ['title' => 'Community Connection', 'text' => 'Participation, transport, and capacity building that help people stay connected to what matters.'],
                ['title' => 'Trusted Coordination', 'text' => 'Clear guidance, reliable communication, and coordinated support from onboarding through ongoing care.'],
            ],
            'hero_cta_label' => 'Book a consultation',
            'hero_cta_url' => '/intake-v2',
            'hero_note' => 'Local, person-centred support for participants, families, carers, and community support workers.',
            'intro_facts' => [
                'NDIS-aligned intake, planning, and service guidance',
                'Qualified workers for home, community, and daily routines',
                'Support coordination across goals, providers, and budgets',
            ],
            'pathways' => [
                ['title' => 'NDIS Services', 'text' => 'Explore practical supports for everyday life.', 'image' => 'contact.jpg', 'url' => '/services-v2'],
                ['title' => 'Join Our Team', 'text' => 'Apply to become an Our Care worker.', 'image' => 'ready.jpg', 'url' => '/healthcare-register'],
                ['title' => 'Start Intake', 'text' => 'Tell us what support you need.', 'image' => 'hero.jpg', 'url' => '/client-register'],
            ],
            'trust_heading' => 'Why clients trust Our Care',
            'trust_text' => 'We are committed to support that feels clear, respectful, and dependable from the first conversation.',
            'trust_items' => [
                ['icon' => '01', 'title' => 'Experienced Guidance', 'text' => 'Support through NDIS options, intake, and planning.'],
                ['icon' => '02', 'title' => 'Personalised Support', 'text' => 'Care shaped around routines, preferences, and goals.'],
                ['icon' => '03', 'title' => 'Up-to-Date Information', 'text' => 'Planning that keeps pace with service changes.'],
                ['icon' => '04', 'title' => 'Trusted and Transparent', 'text' => 'Clear communication before, during, and after support.'],
                ['icon' => '05', 'title' => 'Career-Focused Pathways', 'text' => 'Profile and onboarding support for care workers.'],
                ['icon' => '06', 'title' => 'End-to-End Service', 'text' => 'From first enquiry through matching and support.'],
            ],
            'rating_text' => 'Our Care made support easier to understand and easier to start. The team listened and helped us feel ready.',
            'rating_cta_label' => 'Start your journey today',
            'rating_cta_url' => '/intake-v2',
            'services_heading' => 'Find your support service',
            'events_heading' => 'Join us at an upcoming session',
            'events' => [
                ['kicker' => 'Our Care', 'title' => 'Stay tuned for upcoming information sessions', 'poster_title' => 'Stay tuned for community events', 'meta' => 'Register now', 'image' => 'care-vector-04.png', 'button_label' => 'Register now', 'url' => '/contact-v2'],
                ['kicker' => 'Info Session', 'title' => 'Online session: understanding services and intake', 'poster_title' => 'Plan your NDIS support with confidence', 'meta' => 'Tuesday, 7:00 PM', 'image' => 'contact.jpg', 'button_label' => 'Register now', 'url' => '/intake-v2'],
                ['kicker' => 'Worker Pathway', 'title' => 'Worker session: profile, onboarding, and opportunities', 'poster_title' => 'Study, work, and grow in care', 'meta' => 'Saturday, 10:00 AM', 'image' => 'ready.jpg', 'button_label' => 'Register now', 'url' => '/healthcare-register'],
            ],
            'testimonials_heading' => 'Testimonials',
            'testimonials_text' => 'People choose Our Care because the process feels human, steady, and clear.',
            'testimonials' => [
                ['text' => 'Our support worker is kind, reliable, and respectful of our routine.', 'author' => 'Family carer'],
                ['text' => 'The intake team explained everything in plain language and helped us choose the right services.', 'author' => 'Participant'],
                ['text' => 'I felt supported through registration and onboarding. The worker pathway was clear from the start.', 'author' => 'Support worker'],
            ],
            'requirements_heading' => 'Learn more about NDIS support pathways',
            'requirements' => [
                ['title' => 'Participant Support', 'text' => 'Receive support shaped around daily wellbeing, independence, and personal goals.', 'items' => ['Choose the right service', 'Prepare intake information', 'Understand your support plan', 'Plan worker matching'], 'button_label' => 'Start intake', 'url' => '/client-register'],
                ['title' => 'Worker Pathways', 'text' => 'Join Our Care as a qualified worker and connect with people who need dependable support.', 'items' => ['Build your worker profile', 'Upload qualifications', 'Complete onboarding', 'Apply for care opportunities'], 'button_label' => 'Become a worker', 'url' => '/healthcare-register'],
                ['title' => 'Family Guidance', 'text' => 'Receive clear help for care decisions, provider coordination, and service planning.', 'items' => ['Plan practical supports', 'Coordinate providers', 'Review participant goals', 'Keep communication clear'], 'button_label' => 'Talk to our team', 'url' => '/contact-v2'],
            ],
            'updates_heading' => 'Stay informed: NDIS updates',
            'updates' => [
                ['title' => 'NDIS pricing and support categories', 'text' => 'Keep care planning current as pricing arrangements and support categories change.', 'image' => 'ready.jpg', 'link_label' => 'Read more', 'url' => '/services-v2#ndis'],
                ['title' => 'Preparing for intake with Our Care', 'text' => 'A little preparation helps the team understand goals, routines, and support preferences.', 'image' => 'care-vector-06.png', 'link_label' => 'Read more', 'url' => '/intake-v2'],
                ['title' => 'Choosing services for everyday living', 'text' => 'Explore personal, domestic, transport, and community supports available.', 'image' => 'contact.jpg', 'link_label' => 'Read more', 'url' => '/services-v2'],
            ],
            'cta_title' => 'Get started today',
            'cta_text' => 'Our professional and helpful team is ready to guide the next step for your support needs.',
            'cta_button_label' => 'Book a free consultation',
            'cta_url' => '/intake-v2',
            'cta_image' => 'contact.jpg',
            'office_heading' => 'Find your local office',
            'office_text' => 'We are here to support you online, by phone, and in person.',
            'locations' => ['Sydney', 'Melbourne', 'Brisbane', 'Adelaide'],
            'offices' => [
                ['title' => 'Sydney head office', 'text' => 'Care coordination and participant enquiries', 'email' => 'admin@ourcarepty.com', 'phone' => '0425 795 830'],
                ['title' => 'Melbourne support desk', 'text' => 'Worker onboarding and service information', 'email' => 'admin@ourcarepty.com', 'phone' => '0425 795 830'],
            ],
            'footer_text' => 'Person-centred NDIS support for participants, families, and support workers.',
            'footer_credit' => 'Website and design by Our Care',
        ],
        'about-v2' => [
            'label' => 'About',
            'title' => 'About Our Care',
            'hero_title' => 'A care team built around dignity, choice, and trust.',
            'hero_subtitle' => 'We support people with thoughtful services, reliable systems, and a human approach to care.',
            'hero_image' => 'ready.jpg',
            'intro_title' => 'Who we are',
            'intro_text' => 'Our Care Pty Ltd provides support services that help participants live with confidence, independence, and community connection.',
            'sections' => [
                ['title' => 'Person-centred', 'text' => 'Care plans and services are shaped around each person, their goals, and their preferred routines.'],
                ['title' => 'Reliable', 'text' => 'We value clear communication, consistent support, and dependable follow-through.'],
                ['title' => 'Compassionate', 'text' => 'Every service is delivered with warmth, privacy, respect, and practical care.'],
            ],
        ],
        'services-v2' => [
            'label' => 'Services',
            'title' => 'Our Services',
            'hero_title' => 'Flexible NDIS support for everyday life.',
            'hero_subtitle' => 'Explore personal care, community participation, domestic assistance, transport, counselling, respite, and support coordination.',
            'hero_image' => 'contact.jpg',
            'intro_title' => 'Services',
            'intro_text' => 'Each service can be tailored to the participant, their goals, and the kind of support that makes daily life easier.',
            'sections' => [],
        ],
        'onboarding-v2' => [
            'label' => 'Onboarding',
            'title' => 'Onboarding',
            'hero_title' => 'A clear path from first contact to active support.',
            'hero_subtitle' => 'We make onboarding simple, practical, and centred on the information needed to start care well.',
            'hero_image' => 'ready.jpg',
            'intro_title' => 'Getting started',
            'intro_text' => 'Our onboarding process helps us understand needs, preferences, goals, schedules, and documentation before support begins.',
            'sections' => [
                ['title' => 'Tell us what you need', 'text' => 'Share goals, routines, support needs, and important participant details.'],
                ['title' => 'Plan the service', 'text' => 'We align available supports, timing, workers, and documentation.'],
                ['title' => 'Begin with clarity', 'text' => 'Participants and families know what is happening, who is involved, and what comes next.'],
            ],
        ],
        'intake-v2' => [
            'label' => 'Intake',
            'title' => 'Intake',
            'hero_title' => 'Start your Our Care intake.',
            'hero_subtitle' => 'Share the details we need so the team can understand your support requirements and next steps.',
            'hero_image' => 'hero.jpg',
            'intro_title' => 'Intake information',
            'intro_text' => 'Use intake to begin the care conversation and help our team prepare the right support pathway.',
            'sections' => [
                ['title' => 'Participant details', 'text' => 'Core contact, plan, and support information.'],
                ['title' => 'Support preferences', 'text' => 'Routines, goals, timing, and service priorities.'],
                ['title' => 'Next steps', 'text' => 'Our team reviews the information and follows up with a clear plan.'],
            ],
        ],
        'contact-v2' => [
            'label' => 'Contact',
            'title' => 'Contact Our Care',
            'hero_title' => 'Talk with Our Care.',
            'hero_subtitle' => 'Reach out for service questions, intake support, or help choosing the right pathway.',
            'hero_image' => 'contact.jpg',
            'intro_title' => 'Contact',
            'intro_text' => 'The Our Care team is ready to answer questions and help you take the next step.',
            'sections' => [
                ['title' => 'General enquiries', 'text' => 'Ask about services, availability, or how Our Care can support you.'],
                ['title' => 'Participant support', 'text' => 'Get help with onboarding, intake, and service coordination.'],
                ['title' => 'Worker enquiries', 'text' => 'Healthcare workers can register, manage profiles, and apply for suitable roles.'],
            ],
        ],
    ],
];
