<?php

return [
    'options' => [
        'Acute Care',
        'Activities of Daily Living Assistance',
        'Admissions Coordination',
        'Advanced Cardiac Life Support (ACLS)',
        'Advanced Health Assessment',
        'Advanced Life Support',
        'Advanced Wound Care',
        'Ageing Care',
        'Airway Management',
        'Allergy Testing',
        'Ambulatory Care',
        'Anesthesia Assistance',
        'Anesthesia Monitoring',
        'Antenatal Care',
        'Anticoagulation Management',
        'Aphasia Therapy',
        'Applied Behavior Analysis',
        'Arrhythmia Recognition',
        'Arterial Blood Gas Collection',
        'Aseptic Technique',
        'Assisted Living Care',
        'Asthma Education',
        'Audiometry',
        'Audit and Compliance',
        'Autism Support',
        'Basic Life Support (BLS)',
        'Behavioral Health Support',
        'Bedside Nursing',
        'Biomechanics Assessment',
        'Biopsy Assistance',
        'Bladder Scan Operation',
        'Blood Collection',
        'Blood Glucose Monitoring',
        'Blood Pressure Monitoring',
        'Body Mechanics Training',
        'Breastfeeding Support',
        'Burn Care',
        'Cancer Care Navigation',
        'Cardiac Catheterization Lab Support',
        'Cardiac Monitoring',
        'Cardiopulmonary Resuscitation (CPR)',
        'Care Coordination',
        'Care Planning',
        'Care Transitions',
        'Case Conferencing',
        'Case Management',
        'Catheter Care',
        'Central Line Care',
        'Cerebral Palsy Care',
        'Chemotherapy Administration',
        'Chest Physiotherapy',
        'Chronic Care Management',
        'Chronic Disease Education',
        'Clinical Assessment',
        'Clinical Coaching',
        'Clinical Communication',
        'Clinical Decision Making',
        'Clinical Documentation',
        'Clinical Governance',
        'Clinical Handover',
        'Clinical Informatics',
        'Clinical Monitoring',
        'Clinical Nutrition Support',
        'Clinical Pathology Support',
        'Clinical Research Coordination',
        'Cognitive Assessment',
        'Cognitive Behavioral Therapy',
        'Cold Chain Management',
        'Colostomy Care',
        'Community Health',
        'Community Mental Health',
        'Companionship Care',
        'Compliance Documentation',
        'Conflict De-escalation',
        'Consent Management',
        'Continence Assessment',
        'Continence Care',
        'Contrast Administration',
        'Critical Care Nursing',
        'Critical Thinking in Patient Care',
        'Crisis Intervention',
        'CSSD Sterilization',
        'Cultural Safety',
        'Cupping Therapy',
        'Daily Living Skills Training',
        'Data Privacy in Healthcare',
        'Death and Dying Support',
        'Dementia Care',
        'Dental Assisting',
        'Dental Charting',
        'Dental Radiography',
        'Dental Sterilization',
        'Dermatology Procedures',
        'Developmental Screening',
        'Diabetes Education',
        'Diagnostic Imaging Support',
        'Dialysis Care',
        'Disability Support',
        'Discharge Planning',
        'Documentation Review',
        'Domestic Violence Screening',
        'Donning and Doffing PPE',
        'Doppler Use',
        'Dressing Changes',
        'Drug Calculations',
        'Dysphagia Management',
        'ECG Interpretation',
        'ECG Monitoring',
        'Echocardiography Assistance',
        'Electronic Health Records (EHR)',
        'Emergency Care',
        'Emergency Department Triage',
        'Emergency Response',
        'End of Life Care',
        'Endoscopy Assistance',
        'Enteral Feeding',
        'Environmental Cleaning Oversight',
        'Epidemiology Support',
        'Equipment Sterilization',
        'Exercise Prescription',
        'Fall Prevention',
        'Family Education',
        'Family Planning Counseling',
        'Fetal Monitoring',
        'First Aid',
        'Flu Vaccination',
        'Fluid Balance Monitoring',
        'Foot Care',
        'Forensic Documentation',
        'Gait Training',
        'Gastrostomy Tube Care',
        'General Medicine Support',
        'Geriatric Assessment',
        'Geriatric Care',
        'Grief Support',
        'Group Therapy Facilitation',
        'Gynecology Support',
        'Hand Hygiene Compliance',
        'Health Coaching',
        'Health Education',
        'Health Promotion',
        'Healthcare Scheduling',
        'Hearing Aid Support',
        'Hemodialysis Monitoring',
        'Hemodynamic Monitoring',
        'HIPAA Privacy Awareness',
        'Holistic Care',
        'Home Care',
        'Home Health Assessment',
        'Hospice Care',
        'Hospital Workflow Coordination',
        'ICU Care',
        'Immunization Administration',
        'Incident Reporting',
        'Incontinence Management',
        'Infection Control',
        'Infection Prevention',
        'Infusion Pump Operation',
        'Infusion Therapy',
        'Inhalation Therapy',
        'Inpatient Care',
        'Instrument Handling',
        'Interdisciplinary Collaboration',
        'Interventional Radiology Assistance',
        'Intubation Assistance',
        'IV Cannulation',
        'IV Therapy',
        'Joint Mobilization',
        'Lab Specimen Handling',
        'Lactation Counseling',
        'Leadership in Healthcare',
        'Long-Term Care',
        'Manual Handling',
        'Mass Casualty Triage',
        'Maternal Health',
        'Medical Billing Support',
        'Medical Coding Awareness',
        'Medical Device Handling',
        'Medical Documentation',
        'Medical Ethics',
        'Medical Imaging Preparation',
        'Medical Office Administration',
        'Medical Record Review',
        'Medical Terminology',
        'Medication Administration',
        'Medication Counseling',
        'Medication Reconciliation',
        'Mental Health Assessment',
        'Mental Health Counseling',
        'Microbiology Specimen Collection',
        'Midwifery Support',
        'Mobility Assistance',
        'Motivational Interviewing',
        'MRI Safety Screening',
        'Multidisciplinary Teamwork',
        'Nasogastric Tube Care',
        'Nebulizer Therapy',
        'Neonatal Care',
        'Neuro Rehabilitation',
        'Neurological Assessment',
        'Neurology Support',
        'Newborn Assessment',
        'Nonverbal Patient Support',
        'Nutrition Assessment',
        'Nutrition Counseling',
        'Observation and Reporting',
        'Occupational Therapy Support',
        'Oncology Care',
        'Operating Room Assistance',
        'Orthopedic Care',
        'Ostomy Care',
        'Outbreak Response',
        'Outpatient Care',
        'Oxygen Therapy',
        'Pacemaker Monitoring',
        'Palliative Care',
        'Pain Assessment',
        'Pain Management',
        'Patient Advocacy',
        'Patient Assessment',
        'Patient Centered Care',
        'Patient Counseling',
        'Patient Education',
        'Patient Intake',
        'Patient Mobility Support',
        'Patient Registration',
        'Patient Safety',
        'Pediatric Advanced Life Support (PALS)',
        'Pediatric Care',
        'Pelvic Floor Therapy Support',
        'Perioperative Care',
        'Pharmacology Knowledge',
        'Pharmacy Dispensing Support',
        'Phlebotomy',
        'Physical Assessment',
        'Physical Rehabilitation',
        'Physician Assistance',
        'Point-of-Care Testing',
        'Positioning and Transfers',
        'Post-Anesthesia Care',
        'Postnatal Care',
        'Preoperative Preparation',
        'Pressure Injury Prevention',
        'Primary Care Support',
        'Privacy and Confidentiality',
        'Procedural Assistance',
        'Progress Notes Documentation',
        'Prosthetics Support',
        'Psychiatric Support',
        'Psychological First Aid',
        'Public Health Outreach',
        'Pulse Oximetry',
        'Quality Improvement',
        'Radiation Safety',
        'Radiography Positioning',
        'Rehabilitation Planning',
        'Renal Care',
        'Respiratory Assessment',
        'Respiratory Care',
        'Restraint Monitoring',
        'Rheumatology Support',
        'Risk Assessment',
        'Safeguarding',
        'Sample Labeling',
        'School Health Services',
        'Scrub Assistance',
        'Seizure Management',
        'Self-Care Support',
        'Sensory Integration Support',
        'Sepsis Recognition',
        'Shift Coordination',
        'Skin Assessment',
        'Sleep Study Support',
        'SOAP Notes',
        'Social Work Support',
        'Special Needs Care',
        'Speech Therapy Support',
        'Spirometry',
        'Sports Injury Support',
        'Staff Training',
        'Sterile Field Maintenance',
        'Stoma Care',
        'Stroke Care',
        'Subcutaneous Injection',
        'Substance Use Support',
        'Suicide Risk Screening',
        'Suctioning',
        'Supervision of Support Workers',
        'Surgical Assistance',
        'Surgical Instrument Preparation',
        'Surgical Positioning',
        'Suturing Assistance',
        'Swallowing Assessment Support',
        'Telehealth Support',
        'Temperature Monitoring',
        'Therapeutic Communication',
        'Thrombolysis Preparation',
        'Time Management in Clinical Settings',
        'Tissue Viability Support',
        'Total Parenteral Nutrition Support',
        'Tracheostomy Care',
        'Traction Care',
        'Trauma Care',
        'Triage',
        'Ultrasound Assistance',
        'Urinalysis',
        'Urinary Catheterization',
        'Vaccination Counseling',
        'Vaccination Documentation',
        'Ventilator Monitoring',
        'Venipuncture',
        'Vision Screening',
        'Vital Signs Monitoring',
        'Ward Management',
        'Wheelchair Assistance',
        'Wound Assessment',
        'Wound Care',
        'X-Ray Preparation',
    ],
];
