<?php

return [
    'services' => [
        'personal-care-support' => [
            'label' => 'Personal Care Support',
            'title' => 'Personal Care & Daily Assistance Tailored for you.',
            'heading' => null,
            'image' => 'hero.jpg',
            'summary' => 'Respectful daily living and personal care assistance designed around your routines, comfort, dignity, and independence.',
            'registration' => 'Registration Groups: 0107 Assist-Personal Activities | 0115 Daily Tasks/Shared Living',
            'intro' => [
                'From the morning routine that sets the tone for your day, to preparing a favourite meal, or simply keeping your home feeling fresh and welcoming, these everyday moments matter.',
                'At Our Care, we believe that needing a little extra support should not mean compromising on your independence, choice, or comfort. Our dedicated team is here to walk alongside you, offering respectful, professional daily living and personal care assistance designed to fit seamlessly into your life.',
                'Whether you are looking for short-visit support to help kickstart your morning or comprehensive assistance throughout the day, we map our care to your unique routines and goals.',
            ],
            'section_heading' => 'How We Can Support You',
            'section_intro' => 'Our compassionate support workers are ready to assist with a wide range of daily tasks, always focusing on what makes you feel most comfortable:',
            'items' => [
                ['title' => 'Dignified Personal Care', 'text' => 'Gentle, respectful assistance with showering, dressing, grooming, and personal hygiene. Your privacy and dignity are always our highest priorities.'],
                ['title' => 'Daily Domestic Support', 'text' => 'Helping you maintain a clean, organised, and peaceful living environment, from light cleaning and laundry to organizing your space.'],
                ['title' => 'Meal Preparation & Nutrition', 'text' => 'Cooking healthy, delicious meals that match your dietary preferences and cultural tastes, or working together in the kitchen if you love to cook.'],
                ['title' => 'Routine & Medication Management', 'text' => 'Gentle reminders and practical support to help you manage your daily health routines seamlessly.'],
                ['title' => 'Building Everyday Skills', 'text' => 'If your goal is to learn how to manage certain tasks independently, we are right there to coach and encourage you every step of the way.'],
            ],
        ],
        'community-participation' => [
            'label' => 'Community Participation',
            'title' => 'Community Participation',
            'heading' => null,
            'image' => 'contact.jpg',
            'summary' => 'Support to build confidence, friendships, hobbies, cultural connection, and meaningful participation in the community.',
            'registration' => 'Registration Groups: 0116 Innovative Community Participation | 0125 Participate Community | 0136 Group/Centre Activities',
            'intro' => [
                'Life is richer when we feel connected to the people, places, and activities we love. Whether it is joining a local sports club, attending cultural festivals, catching up with friends at a favorite cafe, or learning a new skill, being active in the community brings a sense of purpose and joy.',
                'At Our Care, we believe that everyone deserves to feel valued, included, and connected. Our community participation support is all about breaking down barriers and opening doors so you can explore your passions, build meaningful relationships, and live life to the absolute fullest.',
            ],
            'section_heading' => 'Ways We Can Explore Together',
            'section_intro' => 'Our friendly, enthusiastic support workers are ready to walk beside you as you step out into the community:',
            'items' => [
                ['title' => 'Social Connections & Friendships', 'text' => 'We can support you in attending social hubs, catching up with loved ones, or joining interest groups where you can meet like-minded people.'],
                ['title' => 'Hobbies & Skill Building', 'text' => 'From art classes and music groups to cooking courses and sports leagues, we help you find and stick with the activities that light you up.'],
                ['title' => 'Cultural & Community Events', 'text' => 'Celebrating identity and heritage matters. We love helping you stay connected to cultural events, community festivals, and faith-based gatherings that are important to you.'],
                ['title' => 'Everyday Outings with Confidence', 'text' => 'Whether it is a trip to the local library, a shopping excursion, or navigating public transport, we provide the steady encouragement you need to feel confident on the move.'],
                ['title' => 'Volunteering & Giving Back', 'text' => 'If you want to contribute to a cause close to your heart, we can help you find and settle into fulfilling volunteer opportunities.'],
            ],
        ],
        'support-coordination' => [
            'label' => 'Support Coordination',
            'title' => 'Support Coordination That Helps You Move Forward',
            'heading' => 'Clear guidance for your NDIS journey',
            'image' => 'ready.jpg',
            'summary' => 'Practical coordination to connect services, strengthen capacity, and help participants use their NDIS plan with confidence.',
            'registration' => 'Registration Group: 0106 Assist-Life Stage, Transition',
            'intro' => [
                'NDIS plans can feel complex when you are trying to balance goals, providers, budgets, routines, and changing life circumstances. Our Care helps make that process clearer and more manageable.',
                'We work alongside participants, families, carers, and providers to coordinate supports that match individual needs and create real progress toward independence, safety, and wellbeing.',
            ],
            'section_heading' => 'How We Coordinate Support',
            'section_intro' => 'Our support coordination is practical, collaborative, and focused on helping you make confident decisions:',
            'items' => [
                ['title' => 'Understanding Your Plan', 'text' => 'We help explain supports, budgets, goals, and service options so you know what is available and how it can be used.'],
                ['title' => 'Connecting Providers', 'text' => 'We assist with finding and coordinating providers that fit your needs, preferences, location, and goals.'],
                ['title' => 'Building Capacity', 'text' => 'We support participants to develop confidence, independence, and the skills needed to manage supports over time.'],
                ['title' => 'Navigating Transitions', 'text' => 'We can assist through changes in education, employment, housing, health, or daily support needs.'],
            ],
        ],
        'domestic-assistance' => [
            'label' => 'Domestic Assistance',
            'title' => 'Domestic Assistance',
            'heading' => 'A Comfortable Home, Nurtured Your Way: Personal Domestic Assistance',
            'image' => 'ready.jpg',
            'summary' => 'Reliable household support that helps participants maintain a safe, clean, organised, and comfortable living environment.',
            'registration' => 'Registration Group: 0120 Household Tasks',
            'intro' => [
                'There is nothing quite like the feeling of a clean, organised, and peaceful home. It is your sanctuary, the place where you unwind, and the backdrop to your daily life. However, keeping on top of everyday household chores can sometimes feel overwhelming or take away the energy you would rather spend on the things you truly love.',
                'At Our Care, we believe that needing a hand around the house should not mean losing your independence. Our Domestic Assistance service is designed to take the stress out of home maintenance, providing the practical, respectful support you need to keep your living space exactly how you like it.',
            ],
            'section_heading' => 'Your Home, Your Routines',
            'section_intro' => 'We know that everyone has their own unique way of running their home. You might like your laundry folded a certain way, or have a specific routine for keeping your kitchen sparkling. We do not come in with a rigid, one-size-fits-all checklist. Instead, we listen to your preferences and work alongside you to maintain your home just the way you want it.',
            'items_heading' => 'How We Can Help Around the House',
            'items_intro' => 'Our compassionate and detail-oriented support workers are ready to assist with a variety of everyday domestic tasks:',
            'items' => [
                ['title' => 'Keeping Spaces Fresh', 'text' => 'Light house cleaning, including dusting, vacuuming, mopping, and wiping down surfaces to keep your environment tidy and hygienic.'],
                ['title' => 'Laundry & Linen Care', 'text' => 'Washing, drying, folding, and ironing your clothes, as well as changing bed linens so you can always enjoy a fresh bed.'],
                ['title' => 'Kitchen & Meal Clean-Up', 'text' => 'Washing dishes, clearing countertops, and maintaining a clean cooking area after meal preparation.'],
                ['title' => 'Organisation & Decluttering', 'text' => 'Helping you organise cupboards, tidy up living areas, and keep your home feeling spacious and manageable.'],
                ['title' => 'Seasonal & Small Errands', 'text' => 'Assisting with grocery unpacking or light household organising that makes your day-to-day life run smoother.'],
            ],
        ],
        'respite' => [
            'label' => 'Respite',
            'title' => 'Respite / Short-Term Accommodation',
            'heading' => 'A Safe Break with Support You Can Trust',
            'image' => 'contact.jpg',
            'summary' => 'Short-term support options that give participants a safe environment and carers time to rest and recharge.',
            'registration' => 'Related to: Accommodation/Tenancy and Daily Living Supports',
            'intro' => [
                'Respite and short-term accommodation can provide a helpful reset for participants, families, and carers. It creates space for rest while keeping support stable, respectful, and goal-focused.',
                'Our Care supports short stays and planned breaks with a focus on comfort, engagement, wellbeing, and confidence.',
            ],
            'section_heading' => 'What Respite Can Include',
            'section_intro' => 'We tailor respite support to the participant, their routines, and their family or carer needs:',
            'items' => [
                ['title' => 'Safe Short Stays', 'text' => 'Supportive environments for planned breaks, transition periods, or short-term accommodation needs.'],
                ['title' => 'Daily Living Support', 'text' => 'Assistance with routines, meals, personal care, medication prompts, and household tasks where required.'],
                ['title' => 'Community Engagement', 'text' => 'Meaningful activities, outings, and social participation during the respite period.'],
                ['title' => 'Carer Relief', 'text' => 'Reliable care that gives families and carers time to rest, reset, or attend to other responsibilities.'],
            ],
        ],
        'employment-capacity' => [
            'label' => 'Employment and Capacity Building',
            'title' => 'Employment and Capacity Building Support',
            'heading' => 'Skills, confidence, and independence for the next step',
            'image' => 'hero.jpg',
            'summary' => 'Support to build life skills, job readiness, communication, confidence, and pathways toward employment goals.',
            'registration' => 'Registration Groups: 0102 Assist Access/Maintain Employment | 0133 Specialist Support Employment | 0117 Development-Life Skills',
            'intro' => [
                'Building independence takes steady support, practical coaching, and opportunities to practise in real life. Our Care helps participants develop skills that support daily confidence and longer-term employment goals.',
                'Whether the focus is job readiness, communication, travel training, routines, or confidence building, we work at a pace that feels achievable.',
            ],
            'section_heading' => 'How We Build Capacity',
            'section_intro' => 'Support can be shaped around the participant’s goals, strengths, and preferred learning style:',
            'items' => [
                ['title' => 'Job Readiness', 'text' => 'Support with workplace expectations, routines, communication, interview preparation, and confidence.'],
                ['title' => 'Life Skills Development', 'text' => 'Practical coaching for everyday tasks, planning, decision-making, and personal independence.'],
                ['title' => 'Workplace Support', 'text' => 'Assistance to access, maintain, and grow in employment opportunities.'],
                ['title' => 'Travel Training', 'text' => 'Building the confidence to move safely between home, community, training, and work.'],
            ],
        ],
        'transport' => [
            'label' => 'Transport Services',
            'title' => 'Transport Services',
            'heading' => 'Your Bridge to the World: Safe, Reliable & Personal Transport Services',
            'image' => 'ready.jpg',
            'summary' => 'Safe, reliable transport support for appointments, work, education, community activities, social outings, and daily needs.',
            'registration' => 'Registration Group: 0108 Assist-Travel/Transport',
            'intro' => [
                'Independence is not just about what you do inside your home. It is about having the freedom to go wherever you want, whenever you want. Whether it is getting to a crucial medical appointment on time, heading to work, visiting family, or simply catching up with friends for a weekend movie, the way you get there matters.',
                'At Our Care, we do not believe that transport is just about getting from point A to point B. We see it as your bridge to the community. Our dedicated transport services are built entirely around your schedule, your comfort, and your peace of mind, ensuring you can travel safely, confidently, and completely on your own terms.',
            ],
            'section_heading' => 'Freedom of Movement, Tailored to You',
            'section_intro' => 'We know that public transport is not always the right fit, and taxis can often feel impersonal or stressful. That is why we map our transport support around your specific lifestyle, preferences, and physical needs. You are in the driver’s seat. We are just here to make the journey smooth and enjoyable.',
            'items_heading' => 'How We Keep You Moving',
            'items_intro' => 'Our reliable support workers offer flexible transport assistance designed to fit seamlessly into your day:',
            'items' => [
                ['title' => 'Everyday Outings & Appointments', 'text' => 'Safe and punctual travel to doctor visits, therapy sessions, grocery shopping, workplaces, or education hubs.'],
                ['title' => 'Social & Community Connections', 'text' => 'Getting you to and from community centres, sports clubs, faith-based gatherings, or social outings with friends and family.'],
                ['title' => 'Accompanied Door-to-Door Care', 'text' => 'Our support workers do not just drop you off at the curb. We assist you out of the house, secure any mobility equipment safely, drive you to your destination, and can stay by your side during your outing if you wish.'],
                ['title' => 'Building Travel Independence', 'text' => 'If your goal is to learn how to use public transport on your own, we offer practical travel training, practising routes, reading timetables, and building the confidence to travel independently.'],
            ],
        ],
        'counselling' => [
            'label' => 'Counselling',
            'title' => 'Counselling',
            'heading' => 'A Safe Space to Heal, Reflect, and Grow: Personal Counselling Built for You',
            'image' => 'contact.jpg',
            'summary' => 'A confidential, respectful space to process life changes, strengthen emotional wellbeing, and build confidence at your own pace.',
            'registration' => 'Mental health and wellbeing support',
            'intro' => [
                'Life is a beautiful journey, but it also comes with seasons that feel heavy, confusing, or deeply overwhelming. Navigating changes, managing everyday anxieties, processing past experiences, or adjusting to new life chapters takes an immense amount of emotional energy. In these moments, having a dedicated space to talk, process, and just be can make all the difference.',
                'At Our Care, we believe that mental well-being is the foundation of a fulfilled life. Our Counselling service is not about clinical diagnoses or checking off standard boxes. It is a warm, entirely confidential, and gentle space where your voice is heard, your experiences are validated, and your unique pace is respected.',
            ],
            'section_heading' => 'Therapy That Honours Your Unique Story',
            'section_intro' => 'We know that no two minds process the world in the exact same way. You bring your own history, your own cultural values, and your own way of communicating. That is why our therapeutic approach is completely tailored around you. We meet you exactly where you are today, without judgment, pressure, or expectations.',
            'items_heading' => 'How We Can Walk Beside You',
            'items_intro' => 'Our compassionate, qualified counsellors are here to support you through a wide range of emotional and life challenges:',
            'items' => [
                ['title' => 'Navigating Life Transitions', 'text' => 'Gentle guidance as you adjust to new environments, changing routines, or major shifts in your care or independence.'],
                ['title' => 'Managing Stress & Anxiety', 'text' => 'Practical, everyday strategies to help you understand your emotional triggers, calm your mind, and regain a sense of grounded control.'],
                ['title' => 'Building Self-Esteem & Identity', 'text' => 'Embracing who you are, discovering your personal strengths, and fostering the self-confidence to advocate for your own needs.'],
                ['title' => 'Strengthening Relationships', 'text' => 'Providing tools to help you communicate your boundaries, connect deeply with loved ones, and build healthy social networks.'],
                ['title' => 'Processing Change and Grief', 'text' => 'A patient, compassionate ear to help you work through feelings of loss, frustration, or burnout at a speed that feels comfortable for you.'],
            ],
        ],
    ],
];
